- hosts: bastion
  tasks:
    - name: Symlink /etc/openstack_deploy directory
      become: true
      file:
        src: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/openstack_deploy"
        dest: /etc/openstack_deploy
        state: link

    - name: Bootstrap deployment host
      become: true
      shell: "SETUP_ARA=true scripts/bootstrap-ansible.sh"
      args:
        chdir: "{{ zuul.projects['git.openstack.org/openstack/openstack-ansible'].src_dir }}"

    - name: Create vault private key tempfile
      become: true
      tempfile:
        state: file
      register: vault_private_key_tmp

    - name: Create vault private key from secret
      become: true
      copy:
        content: "{{ ansible_vault.secret }}"
        dest: "{{ vault_private_key_tmp.path }}"
        mode: 0600

    - name: Run openstack-ansible setup-hosts playbook
      become: true
      shell: "/usr/local/bin/openstack-ansible setup-hosts.yml"
      args:
        chdir: "{{ zuul.projects['git.openstack.org/openstack/openstack-ansible'].src_dir }}/playbooks"
      environment:
        ANSIBLE_VAULT_PASSWORD_FILE: "{{ vault_private_key_tmp.path }}"
        ANSIBLE_CALLBACK_PLUGINS: /etc/ansible/roles/plugins/callback:/opt/ansible-runtime/lib/python2.7/site-packages/ara/plugins/callbacks
        SSH_AUTH_SOCK: "{{ site_bastion.ssh_auth_sock }}"

    - name: Run openstack-ansible setup-infrastructure playbook
      become: true
      shell: "/usr/local/bin/openstack-ansible setup-infrastructure.yml"
      args:
        chdir: "{{ zuul.projects['git.openstack.org/openstack/openstack-ansible'].src_dir }}/playbooks"
      environment:
        ANSIBLE_VAULT_PASSWORD_FILE: "{{ vault_private_key_tmp.path }}"
        ANSIBLE_CALLBACK_PLUGINS: /etc/ansible/roles/plugins/callback:/opt/ansible-runtime/lib/python2.7/site-packages/ara/plugins/callbacks
        SSH_AUTH_SOCK: "{{ site_bastion.ssh_auth_sock }}"

    - name: Run openstack-ansible setup-openstack playbook
      become: true
      shell: "/usr/local/bin/openstack-ansible setup-openstack.yml"
      args:
        chdir: "{{ zuul.projects['git.openstack.org/openstack/openstack-ansible'].src_dir }}/playbooks"
      environment:
        ANSIBLE_VAULT_PASSWORD_FILE: "{{ vault_private_key_tmp.path }}"
        ANSIBLE_CALLBACK_PLUGINS: /etc/ansible/roles/plugins/callback:/opt/ansible-runtime/lib/python2.7/site-packages/ara/plugins/callbacks
        SSH_AUTH_SOCK: "{{ site_bastion.ssh_auth_sock }}"

    - name: Remove vault private key from disk
      become: true
      command: "shred {{ vault_private_key_tmp.path }}"
